blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.generic import RedirectView
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('blogs.urls')),
    path('', RedirectView.as_view(url='blogs/', permanent=True))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register_user, name='register'),
    path('login', views.TheLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/delete', views.user_delete_view, name='user-delete'),
    path('profile/change', views.user_change_view, name='user-change'),
    path('profile/change-password', views.ChangingPasswordView.as_view(), name='password-change'),
    path('post/<int:pk>/comment/', views.add_comment, name='add-comment'),
    path('comment/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
    path('post/<int:pk>/toggle_like/', views.toggle_like, name='toggle_like'),
    path('post/<int:pk>/delete', views.post_delete_view, name='delete-post'),
    path('post/<int:pk>/edit', views.post_change_view, name='edit-post'),
    path('/create', views.PostCreate.as_view(), name='create')
]

blog/blogs/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class ReallyUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True,
                               verbose_name='Аватар', default='avatars/image.png')
    biography = models.CharField(max_length=250, verbose_name="Биография", null=True)

    class Meta(AbstractUser.Meta):
        pass


class Post(models.Model):
    post_text = models.TextField(verbose_name="Текст поста")
    author = models.ForeignKey('ReallyUser', on_delete=models.CASCADE, verbose_name='Автор поста', null=True)
    pub_date = models.DateTimeField(default=datetime.now, verbose_name="Дата публикации")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="liked_posts", blank=True)

    def __str__(self):
        return self.post_text

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    comment_text = models.TextField(verbose_name="Текст комментария")
    post = models.ForeignKey('Post', on_delete=models.CASCADE,
                                      verbose_name="Комментарий к посту", blank=True, null=True)
    commenter = models.ForeignKey('ReallyUser', on_delete=models.CASCADE, verbose_name='Автор комментария', null=True)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/blogs/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import ReallyUser, Comment, Post


class RegistrationForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    biography = forms.CharField(label='Биография', required=False)
    password1 = forms.CharField(label='Пароль', required=True, widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', required=True, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Пароли не совпадают.', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = ReallyUser
        fields = ('username', 'password1', 'password2', 'avatar', 'biography')


class ChangeUserInfoForm(forms.ModelForm):
    biography = forms.CharField(label='Биография', required=False)
    avatar = forms.ImageField(label='Аватар', required=False)

    class Meta:
        model = ReallyUser
        fields = ('username', 'biography', 'avatar')


class CommentForm(forms.Form):
    description = forms.CharField(required=True, label="Комментарий")

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get('description')

        return cleaned_data


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('post_text',)

blog/blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from django.views.generic import CreateView

from .forms import RegistrationForm, ChangeUserInfoForm, CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from .models import Post, Comment


def index(request):
    posts = Post.objects.annotate(comment_count=Count('comment', distinct=True), likes_count=Count('likes', distinct=True)).order_by('-pub_date')[:50]
    paginator = Paginator(posts, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'posts': page.object_list, 'page': page}
    return render(request, 'index.html', context)


def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            print(form.errors)
            return render(request, 'register.html', {'form': form})
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})


class TheLoginView(LoginView):
    template_name = 'login.html'


def logout_view(request):
    logout(request)
    return redirect('/')


@login_required
def profile_view(request):
    posts = Post.objects.filter(author=request.user).order_by('-pub_date')
    paginator = Paginator(posts, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'posts': page.object_list,
        'user': request.user,
        'page': page
    }
    return render(request, 'profile.html', context)


class PostCreate(CreateView):
    model = Post
    template_name = 'create_post.html'
    form_class = PostForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

@login_required
def post_delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        return redirect('index')
    if request.method == 'POST':
        post.delete()
        return redirect(reverse('profile'))
    return render(request, 'delete_post.html', {'post': post})


@login_required
def post_change_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect(reverse('profile'))
        else:
            return render(request, 'change_post.html', {'form': form, 'post': post})
    else:
        form = PostForm(instance=post)
    return render(request, 'change_post.html', {'form': form, 'post': post})


@login_required
def user_delete_view(request):
    user_to_delete = request.user
    if request.method == 'POST':
        user_to_delete.delete()
        return redirect(reverse('index'))
    return render(request, 'delete_user.html', {'user_to_delete': user_to_delete})


@login_required
def user_change_view(request):
    if request.method == 'POST':
        form = ChangeUserInfoForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('profile'))
        else:
            return render(request, 'change_user.html', {'form': form})
    else:
        form = ChangeUserInfoForm(instance=request.user)

    return render(request, 'change_user.html', {'form': form})


class ChangingPasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'password_change.html'
    success_url = reverse_lazy('profile')


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data.get('description')
            Comment.objects.create(
                post=post,
                comment_text=comment_text if comment_text else '',
                commenter=request.user
            )
            return redirect('index')
        else:
            pass
    else:
        form = CommentForm()
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'add_comment.html', context)


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.user != comment.commenter:
        return redirect('index')

    if request.method == 'POST':
        comment.delete()
        return redirect('index')

    return redirect('index')


@login_required
def edit_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.user != comment.commenter:
        return redirect('index')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment.comment_text = form.cleaned_data['description']
            comment.save()
            return redirect('index')
    else:
        form = CommentForm(initial={'description': comment.comment_text})

    context = {'form': form, 'comment': comment}
    return render(request, 'edit_comment.html', context)


@login_required
def toggle_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user

    if user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)

    return redirect('index')

blog/blogs/templates/add_comment.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Создание комментария</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <div class="calculator-form another">
                                    <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Отправить" class="button"/>
                                </form>
                                </div>

                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% else %}
<section class="title">
    <h3>Пожалуйста, войдите в аккаунт.</h3>
</section>
{% endif %}
{% endblock %}

blog/blogs/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Блог{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo">
                <a href="/">
                    <span>БлогПлатформа</span>
                </a>
            </div>
             <nav class="header-nav">
                <a href="{% url 'index' %}">главная</a>
                {% if user.is_authenticated %}
                <p class="like-link">пользователь: {{ user.get_username }}</p>
                <a href="{% url 'profile' %}">профиль</a>
                <a href="{% url 'logout' %}">выйти из профиля</a>
                <a href="{% url 'create' %}">создать пост</a>
                 <a href="{% url 'user-change' %}">редактировать профиль</a>
                 <a href="{% url 'user-delete' %}">удалить профиль</a>
                {% else %}
                    <a href="{% url 'login' %}">войти</a>
                    <a href="{% url 'register' %}">регистрация</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="main">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="footer">
        <nav class="nav">
                    <a href="{% url 'index' %}">Главная</a>
                {% if user.is_authenticated %}
                <p class="like-link-f">Пользователь: {{ user.get_username }}</p>
                <a href="{% url 'profile' %}">Профиль</a>
                {% else %}
                    <a href="{% url 'login' %}">Войти</a>
                    <a href="{% url 'register' %}">Регистрация</a>
                {% endif %}
            </nav>
        <div class="container">
            <p>&copy; 2025 БлогПлатформа. Все права защищены.</p>
        </div>
    </footer>
</body>
</html>

blog/blogs/templates/change_post.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>редактирование поста</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">сохранить изменения</button>
    </form>
{% endblock %}

blog/blogs/templates/change_user.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Правка личных данных пользователя</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <h3 class="article-text">Аватар пользователя</h3>
                {% if user.avatar %}
<img src="{{ user.avatar.url }}" alt="Аватар пользователя" class="prof-img">
    {% else %}
    {% endif %}
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <div class="calculator-form">
                                    <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Сохранить" class="button"/>
                                </form>
                                </div>

                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% else %}
<section class="title">
    <h3>Пожалуйста, войдите в аккаунт.</h3>
</section>
{% endif %}
{% endblock %}

blog/blogs/templates/create_post.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Создание поста</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <div class="calculator-form another">
                                    <form action="" method="post" enctype="multipart/form-data" class="calculator-form-inner">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Сохранить" class="button"/>
                                </form>
                                </div>

                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% else %}
<section class="title">
    <h3>Пожалуйста, войдите в аккаунт.</h3>
</section>
{% endif %}
{% endblock %}

blog/blogs/templates/delete_post.html
{% extends "base_generic.html" %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
<div class="delete-confirmation">
    <h1>Удалить пост</h1>
    
    <div class="post-preview">
        <p>{{ post.content|truncatechars:200 }}</p>
        <p class="post-info">Создан: {{ post.created_at|date:"d.m.Y H:i" }}</p>
        <p class="post-info">Лайков: {{ post.likes_count }}, Комментариев: {{ post.comments_count }}</p>
    </div>
    
    <p class="warning">Вы уверены, что хотите удалить этот пост? Это действие нельзя отменить.</p>
    
    <form method="post">
        {% csrf_token %}
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Да, удалить</button>
            <a href="/post/{{ post.id }}/" class="btn btn-secondary">Отмена</a>
        </div>
    </form>
</div>
{% endblock %}

blog/blogs/templates/delete_user.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Удаление пользователя</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <h3 class="article-text">Вы уверены, что хотите удалить свой аккаунт?</h3>
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <div class="calculator-form" id="conff">
                                    <form action="" method="post" class="calculator-form-inner" id="conf">
                                    {% csrf_token %}
                                    {{ form.as_div }}
                                    <input type="submit" value="УДАЛИТЬ" class="button"/>
                                </form>
                                </div>
                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% else %}
<section class="title">
    <h3>Пожалуйста, войдите в аккаунт.</h3>
</section>
{% endif %}
{% endblock %}

blog/blogs/templates/edit_comment.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Изменение поста</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <div class="calculator-form another">
                                    <form action="" method="post" enctype="multipart/form-data" >
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="СОХРАНИТЬ" class="button"/>
                                </form>
                                </div>

                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% else %}
<section class="title">
    <h3>Пожалуйста, войдите в аккаунт.</h3>
</section>
{% endif %}
{% endblock %}

blog/blogs/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<section class="title">
            <h1>Все посты</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    {% if posts %}
                    {% for post in posts %}
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <h3>Автор поста: {{ post.author }}</h3>
                                <p>{{ post.post_text }}</p>
                                <p>Дата создания: {{ post.pub_date }}</p>
                                 {% if request.user.is_authenticated %} {# Только для авторизованных пользователей #}
            <p class="lele">
                <a href="{% url 'toggle_like' pk=post.pk %}">
                    {% if request.user in post.likes.all %}
                        Уже не нравится
                    {% else %}
                        Нравится
                    {% endif %}
                    {% if request.user == post.author %}
                        <a href="{% url 'edit-post' pk=post.pk %}" class="change"><b>Изменить пост?</b></a>
                        <a href="{% url 'delete-post' pk=post.pk %}" class="change"><b>Удалить пост?</b></a>
                    {% endif %}
                </a>
                <span>Отметок "нравится": {{ post.likes_count }}</span>
            </p>
        {% else %}
            <p>Отметок "нравится": {{ post.likes_count }}</p>
        {% endif %}

        <p>Комментарии: {{ post.comment_count }}</p>

                            </div>
                            <div class="article-buttons">
                                {% for comment in post.comment_set.all %}
        <p class="comment">{{ comment.commenter.username }}: {{ comment.comment_text }}</p>
                                 {% if request.user == comment.commenter %}
                            <a href="{% url 'edit-comment' pk=comment.pk %}" class="change"><b>Изменить комментарий?</b></a>
                            <form action="{% url 'delete-comment' pk=comment.pk %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Удалить комментарий" class="button"/>
                            </form>
                        {% endif %}
    {% endfor %}
                                <a href="{% url 'add-comment' pk=post.pk %}" class="button">проккоментировать</a>
                            </div>
                            <div class="line"></div>
                            {% endfor %}
                            {% if page.paginator.num_pages > 1 %}
    <div class="pagination">
        <div class="pagination-list">
            {% if page.has_previous %}
                <div class="pagination-item">
                    <a href="?page={{ page.previous_page_number }}" class="pagination-link">&laquo;</a>
                </div>
            {% endif %}


            {% for num in page.paginator.page_range %}
                <div class="pagination-item {% if num == page.number %}active{% endif %}">
                    {% if num == page.number %}
                        <span class="pagination-link">{{ num }}</span>
                    {% else %}
                        <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                    {% endif %}
                </div>
            {% endfor %}

            {% if page.has_next %}
                <div class="pagination-item">
                    <a href="?page={{ page.next_page_number }}" class="pagination-link">&raquo;</a>
                </div>
            {% endif %}
        </div>
    </div>
                            {% endif %}
                            {% else %}
                             <p>Нет постов </p>
                            {% endif %}
                        </div>
                    </article>

                </div>
            </div>
        </section>
{% endblock %}

blog/blogs/templates/login.html
{% extends "base_generic.html" %}

{% block content %}
<section class="title">
            <h1>Вход</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    {% if user.is_authenticated %}
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <h3>Вы уже вошли.</h3>
                                {% else %}
                                <div class="calculator-form">
                                    <form action="" method="post" enctype="multipart/form-data" class="calculator-form-inner">
                                    {% csrf_token %}
                                    <p>{{ form.username.label_tag }}</p>
                                      <p>{{ form.username }}</p>
                                      <p>{{ form.password.label_tag }}</p>
                                      <p>{{ form.password }}</p>
                                    <input type="submit" value="ВОЙТИ" class="button"/>
                                </form>
                                </div>
                                {% endif %}
                            </div>

                        </div>
                    </article>
                </div>
            </div>
        </section>
{% endblock %}

blog/blogs/templates/logout.html
{% extends "basic.html" %}
{% block content %}
    <h2>редактирование поста</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">сохранить изменения</button>
    </form>
{% endblock %}

blog/blogs/templates/password_change.html
{% extends "base_generic.html" %}

{% block content %}
<section class="title">
            <h1>Смена пароля</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <div class="four-articles">
                    <article>
                        <div class="article-inner">
                            <div class="article-text">

                                <div class="calculator-form">
                                    <form method="post" class="calculator-form-inner">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="СМЕНИТЬ ПАРОЛЬ" class="button"/>
                                </form>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </section>
{% endblock %}

blog/blogs/templates/profile.html
{% extends "base_generic.html" %}

{% block content %}

{% if user.is_authenticated %}
<section class="title">
            <h1>Ваш профиль</h1>
        </section>
        <section class="articles-wrapper">
            <div class="articles">
                <h3 class="article-text">Аватар пользователя {{ user.username }} </h3>
                <h3 class="article-text">Биография: {{ user.biography }}</h3>
                {% if user.avatar %}
<img src="{{ user.avatar.url }}" alt="Аватар пользователя" class="prof-img">
    {% else %}
    {% endif %}
                <div class="four-articles">
                    {% if posts %}
                    {% for post in posts %}
                    <article>
                        <div class="article-inner">
                            <div class="article-text">
                                <h3>Автор поста: {{ post.author }}</h3>
                                <p>{{ post.post_text }}</p>
                                <p>Дата создания: {{ post.pub_date }}</p>
                                 {% if request.user.is_authenticated %} {# Только для авторизованных пользователей #}
            <p class="lele">
                <a href="{% url 'toggle_like' pk=post.pk %}">
                    {% if request.user in post.likes.all %}
                        Уже не нравится
                    {% else %}
                        Нравится
                    {% endif %}
                </a>
                <span>Отметок "нравится": {{ post.likes_count }}</span>
            </p>
        {% else %}
            <p>Отметок "нравится": {{ post.likes_count }}</p>
        {% endif %}

        <p>Комментарии: {{ post.comment_count }}</p>

                            </div>
                            <div class="article-buttons">
                                {% for comment in post.comment_set.all %}
        <p class="comment">{{ comment.commenter.username }}: {{ comment.comment_text }}</p>
                                 {% if request.user == comment.commenter %}
                            <a href="{% url 'edit-comment' pk=comment.pk %}" class="change"><b>Изменить комментарий?</b></a>
                            <form action="{% url 'delete-comment' pk=comment.pk %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Удалить комментарий" class="button"/>
                            </form>
                        {% endif %}
    {% endfor %}
                                <a href="{% url 'add-comment' pk=post.pk %}" class="button">Проккоменитровать</a>
                            </div>
                            <div class="line"></div>
                            {% endfor %}
                            {% if page.paginator.num_pages > 1 %}
    <div class="pagination">
        <div class="pagination-list">
            {% if page.has_previous %}
                <div class="pagination-item">
                    <a href="?page={{ page.previous_page_number }}" class="pagination-link">&laquo;</a>
                </div>
            {% endif %}


            {% for num in page.paginator.page_range %}
                <div class="pagination-item {% if num == page.number %}active{% endif %}">
                    {% if num == page.number %}
                        <span class="pagination-link">{{ num }}</span>
                    {% else %}
                        <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                    {% endif %}
                </div>
            {% endfor %}

            {% if page.has_next %}
                <div class="pagination-item">
                    <a href="?page={{ page.next_page_number }}" class="pagination-link">&raquo;</a>
                </div>
            {% endif %}
        </div>
    </div>
                            {% endif %}
                            {% else %}
                             <p>Нет постов </p>
                            {% endif %}
                        </div>
                    </article>

                </div>
            </div>
        </section>
{% endif %}
{% endblock %}